version: '3.5'

services:
  nexus:
    image: 'sonatype/nexus3:3.15.2'
    container_name: 'nexus'
    restart: always
    ports: 
      - '8081:8081'
    volumes:
      - nexus:/nexus-data

volumes:
  nexus: